name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'   # dispara em tags como v2.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get version from tag
        id: get_version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack Matheus.SortAlgorithms
        run: dotnet pack ./Matheus.SortAlgorithms/Matheus.SortAlgorithms.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Publish Matheus.SortAlgorithms to NuGet
        run: dotnet nuget push ./artifacts/Matheus.SortAlgorithms.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
